# Generated by Django 5.2.11 on 2026-03-27 04:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stories", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="messagethread",
            name="admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_threads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="messagethread",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_threads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="thread",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="stories.messagethread",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="hashtags",
            field=models.ManyToManyField(
                blank=True, related_name="stories", to="stories.hashtag"
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="messagethread",
            name="story",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threads",
                to="stories.story",
            ),
        ),
        migrations.AddField(
            model_name="storydocument",
            name="story",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="stories.story",
            ),
        ),
        migrations.AddField(
            model_name="storymedia",
            name="story",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="media",
                to="stories.story",
            ),
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(fields=["status"], name="stories_status_a9167d_idx"),
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["user", "status"], name="stories_user_id_cdc756_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="messagethread",
            unique_together={("story", "user")},
        ),
    ]
