# Generated by Django 5.2.11 on 2026-03-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0004_adminlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
