# Generated by Django 5.2.11 on 2026-03-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stories", "0005_story_is_featured"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(blank=True, max_length=100)),
                ("quote", models.TextField()),
                ("avatar_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "testimonials",
                "ordering": ["order", "-created_at"],
            },
        ),
    ]
